use_frameworks!

platform :ios, '11.0'

target 'SwiftyCamera_Example' do
  pod 'SwiftyCamera', :path => '../'
  pod 'SnapKit'

  target 'SwiftyCamera_Tests' do
    inherit! :search_paths

    
  end
end
